baseURL = "https://www.beyondinfinitystudio.com"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Beyond Infinity Games"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Beyond Infinity Games](https://www.beyondinfinitystudio.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.main]]
URL = "#about"
name = "about"
weight = 1
[[menu.main]]
URL = "games"
name = "games"
weight = 2
[[menu.main]]
URL = "#portfolio"
name = "portfolio"
weight = 3
[[menu.main]]
URL = "#team"
name = "team"
weight = 4
[[menu.main]]
URL = "pricing"
name = "pricing"
weight = 5
[[menu.main]]
URL = "blog"
name = "blog"
weight = 6
[[menu.main]]
URL = "contact"
name = "contact"
weight = 7
[[menu.static]]
[params]
author = "Rizwan"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analytics_id = ""
logo = "images/beyond-infinity-games-menu-logo.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/beyond-infinity-games-menu-logo.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/BeyondInfinityGamesOfficial"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/beyondinfinitygames/"
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UC9JiP_hUsXNx6grIk3b2SyA?"
[[params.social]]
icon = "ti-android"
link = "https://play.google.com/store/apps/developer?id=Beyond+Infinity+Studios"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
